export const APPLICATION_NAME = 'Dev Learning Hub';

export const MONGO_URI: string = process.env.MONGO_URI || 'localhost:27017';

export const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL || 'http://localhost:3000';

export const GET_COURSES_WITH_PAGINATION_PAGE_SIZE = 4;

export const GET_TECHNOLOGIES_WITH_PAGINATION_PAGE_SIZE = 6;

export const GET_INTERVIEW_QUESTIONS_WITH_PAGINATION_PAGE_SIZE = 7;

export const PAGINATION_DEFAULT_INITIAL_PAGE = 1;

export const GET_CODE_SNIPPETS_WITH_PAGINATION_PAGE_SIZE = 9;

export const GET_COMMUNITY_REQUESTS_WITH_PAGINATION_PAGE_SIZE = 10;

export const COMMUNITY_REQUEST_APPROVES_REQUIRED = 1;
